### ISSUE TITLE
Some TV channel not working

### ISSUE THREAD

**Issue by Drealine** [fabianishere/udm-iptv#218] opened 2023-01-23 12:27 UTC
### What is your ISP? (if relevant)

Bouygues Telecom (French)

### Diagnostic Information

Some logs are ok but we see this error sometimes : MRT_DEL_MFC; Errno(2): No such file or directory

### Describe the Bug

Some TV channel work and anothers not.
Maybe a problem with route cache ?

### Expected Behavior

I've set rule to allow IGMP from WAN interface
Set WAN IP to 0.0.0.0/0. ISP need this.

**Comment by Drealine** [comment] 2023-01-23 12:31
Ok, it stay on TV channel for 5 minutes, the channel TV going to black screen.
Need to reload igmpproxy.

Running on UDM PRO SE Network v 7.3.81

**Comment by Drealine** [comment] 2023-01-23 16:40
See logs output from tcpdump captured multicast:

17:38:07.661545 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    i15-lef02-ix2-87-90-202-182.ft.lns.abo.bbox.fr > igmp.mcast.net: igmp v3 report, 1 group record(s) [gaddr 224.0.1.187 to_in { }]
17:38:07.851523 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    i15-lef02-ix2-87-90-202-182.ft.lns.abo.bbox.fr > igmp.mcast.net: igmp v3 report, 1 group record(s) [gaddr 224.0.1.187 to_ex { }]
17:38:08.091515 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 40, options (RA))
    i15-lef02-ix2-87-90-202-182.ft.lns.abo.bbox.fr > igmp.mcast.net: igmp v3 report, 1 group record(s) [gaddr 224.0.1.187 to_ex { }]
17:38:15.832947 IP (tos 0x0, ttl 1, id 30314, offset 0, flags [DF], proto UDP (17), length 32)
    i15-lef02-ix2-87-90-202-182.ft.lns.abo.bbox.fr.43494 > 233.89.188.1.10001: [bad udp cksum 0xc789 -> 0x6672!] UDP, length 4
17:38:26.382000 IP (tos 0x0, ttl 1, id 31305, offset 0, flags [DF], proto UDP (17), length 32)
    i15-lef02-ix2-87-90-202-182.ft.lns.abo.bbox.fr.43494 > 233.89.188.1.10001: [bad udp cksum 0xc789 -> 0x6672!] UDP, length 4


Some packets are bad udp cksum. Why ?

**Comment by fabianishere** [comment] 2023-01-23 18:56
Duplicate of #123. Please try to move the STB to a separate VLAN if possible.

**Closed by fabianishere** 2023-01-23 18:56 UTC
Labels: kind/bug
